/**
 * SIMULATED PROVIDER — NOT A REAL MODEL.
 *
 * Used only in browser demo mode, where there is no API, no database and no
 * model backend. Every reply is generated by the rules below; nothing is sent
 * anywhere and no inference happens.
 *
 * It is deliberately NOT written to sound like a language model. Text that
 * imitated a real answer would be indistinguishable from one, which is exactly
 * the fabrication spec §131 forbids. Instead it reports what the system did.
 */
import type { RegisteredModel } from "./core-imports.ts";

/** Per-model character delay, so a "fast" model visibly streams faster. */
function delayFor(model: RegisteredModel): number {
  return Math.max(6, 46 - model.scores.speed * 4);
}

export interface SimulatedRun {
  text: string;
  /** Milliseconds between emitted chunks. */
  delayMs: number;
  inputTokens: number;
  outputTokens: number;
}

/** Sending this makes the chosen model fail, so fallback can be demonstrated. */
export const FAIL_TRIGGER = "/fail";

export function simulate(model: RegisteredModel, prompt: string, estimatedInputTokens: number): SimulatedRun {
  const where = model.local ? "on this machine" : `at ${model.providerId}`;
  const price =
    model.inputCostPer1m === 0 && model.outputCostPer1m === 0
      ? "It is free to run."
      : `It is priced at $${model.inputCostPer1m}/$${model.outputCostPer1m} per million input/output tokens.`;

  const text =
    `[simulated — no model was called]\n\n` +
    `The router selected ${model.displayName}, which runs ${where}. ${price} ` +
    `Its context window is ${model.contextWindow.toLocaleString()} tokens, and your message was ` +
    `estimated at ${estimatedInputTokens}.\n\n` +
    `Everything above — the ranking, the privacy filter, the fallback chain, the cost estimate — ` +
    `came from NYRO's real routing code running in this page. Only the reply text is simulated, ` +
    `because a browser has no model to call.`;

  return {
    text,
    delayMs: delayFor(model),
    inputTokens: estimatedInputTokens,
    // Roughly 4 characters per token, matching the estimator in the real system.
    outputTokens: Math.ceil(text.length / 4),
  };
}

export function shouldFail(prompt: string): boolean {
  return prompt.trim().toLowerCase().includes(FAIL_TRIGGER);
}
